apiVersion: v1
kind: Service
metadata:
  name: frontend_angular
spec:
  selector:
    app: frontend_angular
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 4200
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend_angular
spec:
  selector:
    matchLabels:
      app: frontend_angular
  replicas: 4
  template:
    metadata:
      labels:
        app: frontend_angular
    spec:
      containers:
      - name: frontend_angular
        image: frondend_angular:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4200
